### PR TITLE
MooseFS SM driver for 2.30.3 8.2

### PR DESCRIPTION
**Pull request by xandrus**

### CODE REVIEW

**Comment by stormi** [comment]
Thanks @xandrus. @Wescoeur will do a last pass of review.

We'll want this change to be contained in just one commit, for a cleaner git history. You can either squash your commits manually (git rebase -i ...) or we'll push the "Squash and merge" button when merging the PR, depending on what you prefer.

**Comment by xandrus** [comment]
Hi!
I have just made a squash all the commits.
Thank you for all the information and suggestions!

**Comment by Wescoeur** [comment]
I merged your PR, thank you for your contribution. If you have any changes to add, feel free to open a new merge request. :slightly_smiling_face: 

The driver will be available in the next package update.

**Comment by stormi** [comment]
@xandrus @pkonopelko Hi! We have included the driver in the last update candidates for XCP-ng 8.2 (see https://xcp-ng.org/forum/topic/365/updates-announcements-and-testing/281) so it will be soon available for every XCP-ng 8.2 user, and it occurs to me that we need one last contribution for the driver to be really seen as available by our users: documentation.

Could you contribute a PR to our documentation at https://xcp-ng.org/docs/storage.html?

You need to add changes in two places:
1) Add MooseFS to the table (last in its category) at https://xcp-ng.org/docs/storage.html#storage-types 
2) Add a MooseFS subsection to the document where appropriate (same order as in table).

The documentation needs not explain how to setup MooseFS on the remote server side but it can link to the official documentation for it. A short introduction explaining what MooseFS is is allowed as long as it's not turned like an advertisement (no superlatives) :). The doc must tell users how to enable the `sm` driver for MooseFS, because it's not enabled by default (you need to edit the `sm-plugins=` line in `/etc/xapi.conf`...). And, of course, it must explain how to create a SR.

**Comment by stormi** [comment]
The doc must also detail what to install on the XCP-ng hosts and where from: `moosefs-client` and maybe more?

It's probably also good to specify that the SR driver was contributed directly by MooseFS developers.

**Comment by xandrus** [comment]
Hi,
Thank you for all the information!
Of course we have to add documentation and we will prepare pull request with instructions how to set up all components together.

**Pull request merged**
